# Generated by Django 2.1 on 2020-04-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Algorithem', models.CharField(max_length=255)),
                ('Style', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=255)),
                ('Length', models.IntegerField()),
                ('Paper', models.CharField(max_length=1024)),
            ],
        ),
    ]
