# Generated by Django 2.1 on 2020-04-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Snippet',
        ),
    ]
